version: '3.9'
services:
  database:
    build: magnesie-image-storage/database
    volumes: 
      - databaseStorage:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  result-storage-webservice:
    depends_on:
      - database
    build: magnesie-result-storage
    volumes:
      - hostedFiles:/hostedFiles
    ports:
      - ${RESULT_STORAGE_WS_PORT}:7881
    environment:
      - ROCKET_DATABASES={rocket_app={url="mysql://magnesie_result_storage:password@database:3307/magnesie_result_storage"}}
      - ROCKET_PORT=7881
    command: sh -c '/bin/wait-for.sh database:3307 -t 90 -- /usr/local/bin/webservice'

  image-storage-webservice:
    depends_on:
      - result-storage-webservice
    build: magnesie-image-storage/webservice
    volumes:
      - hostedFiles:/hostedFiles
    ports:
      - ${IMAGE_STORAGE_WS_PORT}:7880
    environment:
      - ROCKET_DATABASES={rocket_app={url="mysql://magnesie_image_storage:password@database:3307/magnesie_image_storage"}}
      - ROCKET_PORT=7880
      - HOSTED_FILES_FOLDER=/hostedFiles
    command: sh -c '/bin/wait-for.sh result-storage-webservice:7881 -t 90 -- /usr/local/bin/webservice'

  photogrammetry:
    image: ghcr.io/magnesie-v2/photogrammetry
    privileged: true
    ports:
      - ${PHOTOGRAMMETRY_WS_PORT}:8000
    volumes:
      - photogrammetryLogs:/logs

  api-seduce-mock:
    build: back-end-mocks
    ports:
      - 7882:7882

  orchestrator:
    depends_on:
      - image-storage-webservice
      - result-storage-webservice
      - photogrammetry
    build: magnesie-orchestrator
    ports:
      - ${ORCHESTRATOR_WS_PORT}:7878
    environment:
      - IMAGE_STORAGE_WS_HOST=image-storage-webservice
      - IMAGE_STORAGE_WS_PORT=7880
      - RESULT_STORAGE_WS_HOST=result-storage-webservice
      - RESULT_STORAGE_WS_PORT=7881
      - PHOTOGRAMMETRY_WS_HOST=photogrammetry
      - PHOTOGRAMMETRY_WS_PORT=8000
      - SEDUCE_API_HOST=api-seduce-mock
      - SEDUCE_API_PORT=7882
      - ORCHESTRATOR_WS_HOST=orchestrator
      - ORCHESTRATOR_WS_PORT=7878
    command: sh -c 'bash /bin/wait-for.sh image-storage-webservice:7880 -t 90 -- ./magnesie-orchestrator'

volumes:
  databaseStorage: {}
  hostedFiles: {}
  photogrammetryLogs: {}